In [1]:
import polars as pl
import pandas as pd
import numpy as np

## Data

In [2]:
data_url = "https://raw.githubusercontent.com/FabioScielzoOrtiz/PyDistances-demo/refs/heads/main/data/madrid_houses_processed.csv"

In [ ]:
multiclass_cols = ['energy_certificate', 'house_type']

In [4]:
data_pl = pl.read_csv(data_url)
data_pl.head()

shape: (5, 11)
┌────────────┬─────────┬────────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sq_mt_buil ┆ n_rooms ┆ n_bathroom ┆ n_floors ┆ … ┆ is_exteri ┆ has_parki ┆ energy_ce ┆ house_typ │
│ t          ┆ ---     ┆ s          ┆ ---      ┆   ┆ or        ┆ ng        ┆ rtificate ┆ e         │
│ ---        ┆ i64     ┆ ---        ┆ i64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64        ┆         ┆ i64        ┆          ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64       │
╞════════════╪═════════╪════════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 64.0       ┆ 2       ┆ 1          ┆ 1        ┆ … ┆ 1         ┆ 0         ┆ 4         ┆ 0         │
│ 70.0       ┆ 3       ┆ 1          ┆ 1        ┆ … ┆ 1         ┆ 0         ┆ 0         ┆ 0         │
│ 94.0       ┆ 2       ┆ 2          ┆ 1        ┆ … ┆ 1         ┆ 0         ┆ 0         ┆ 0         │
│ 64.0       ┆ 2       ┆ 1          ┆ 1        ┆ … ┆ 1         ┆ 0         ┆ 0         ┆ 0         │
│ 108.0      ┆ 2       ┆ 2          ┆ 1        ┆ … ┆ 1         ┆ 1         ┆ 0         ┆ 0         │
└────────────┴─────────┴────────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
data_pd = pd.read_csv(data_url)
data_pd.head()

sq_mt_built  n_rooms  n_bathrooms  n_floors  buy_price  is_renewal_needed  \
0         64.0        2            1         1      85000                  0   
1         70.0        3            1         1     129900                  1   
2         94.0        2            2         1     144247                  0   
3         64.0        2            1         1     109900                  0   
4        108.0        2            2         1     260000                  0   

   has_lift  is_exterior  has_parking  energy_certificate  house_type  
0         0            1            0                   4           0  
1         1            1            0                   0           0  
2         1            1            0                   0           0  
3         1            1            0                   0           0  
4         1            1            1                   0           0

In [18]:
data_np = np.array(data_pd[multiclass_cols])
data_np

array([[4, 0],
       [0, 0],
       [0, 0],
       ...,
       [3, 0],
       [0, 1],
       [7, 0]])

In [19]:
xi_pl = data_pl[multiclass_cols][2,:]
xr_pl = data_pl[multiclass_cols][10,:]

In [13]:
xi_pd = data_pd[multiclass_cols].iloc[2,:]
xr_pd = data_pd[multiclass_cols].iloc[10,:]

In [20]:
xi_np = data_np[2,:]
xr_np = data_np[10,:]

## `hamming_dist_matrix`

In [6]:
from PyDistances.multiclass import hamming_dist_matrix

In [16]:
hamming_dist_matrix(X=data_pl[multiclass_cols])

array([[0. , 0.5, 0.5, ..., 0.5, 1. , 0.5],
       [0.5, 0. , 0. , ..., 0.5, 0.5, 0.5],
       [0.5, 0. , 0. , ..., 0.5, 0.5, 0.5],
       ...,
       [0.5, 0.5, 0.5, ..., 0. , 1. , 0.5],
       [1. , 0.5, 0.5, ..., 1. , 0. , 1. ],
       [0.5, 0.5, 0.5, ..., 0.5, 1. , 0. ]])

In [7]:
hamming_dist_matrix(X=data_pd[multiclass_cols])

array([[0. , 0.5, 0.5, ..., 0.5, 1. , 0.5],
       [0.5, 0. , 0. , ..., 0.5, 0.5, 0.5],
       [0.5, 0. , 0. , ..., 0.5, 0.5, 0.5],
       ...,
       [0.5, 0.5, 0.5, ..., 0. , 1. , 0.5],
       [1. , 0.5, 0.5, ..., 1. , 0. , 1. ],
       [0.5, 0.5, 0.5, ..., 0.5, 1. , 0. ]])

In [21]:
hamming_dist_matrix(X=data_np)

array([[0. , 0.5, 0.5, ..., 0.5, 1. , 0.5],
       [0.5, 0. , 0. , ..., 0.5, 0.5, 0.5],
       [0.5, 0. , 0. , ..., 0.5, 0.5, 0.5],
       ...,
       [0.5, 0.5, 0.5, ..., 0. , 1. , 0.5],
       [1. , 0.5, 0.5, ..., 1. , 0. , 1. ],
       [0.5, 0.5, 0.5, ..., 0.5, 1. , 0. ]])

## `hamming_dist`

In [11]:
from PyDistances.multiclass import hamming_dist

In [22]:
hamming_dist(xi=xi_pl, xr=xr_pl)

np.float64(0.0)

In [14]:
hamming_dist(xi=xi_pd, xr=xr_pd)

np.float64(0.0)

In [23]:
hamming_dist(xi=xi_np, xr=xr_np)

np.float64(0.0)