In [13]:
pip show PyDistances

Name: PyDistances
Version: 0.0.29
Summary: PyDistances is a Python package for computing classic statistical distances as well as new proposals suitable for mixed multivariate data, even with outliers.
Home-page: https://github.com/FabioScielzoOrtiz/PyDistances-package
Author: Fabio Scielzo Ortiz
Author-email: fabioscielzo98@gmail.com
License: 
Location: c:\Users\fscielzo\Documents\Proyectos\PyDistances\PyDistances-demo\.venv\Lib\site-packages
Requires: 
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [7]:
import polars as pl
import pandas as pd
import numpy as np

In [ ]:
data_url = ""

In [9]:
data_pl = pl.read_csv(data_path)
data_pl.head()

shape: (5, 11)
┌────────────┬─────────┬────────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sq_mt_buil ┆ n_rooms ┆ n_bathroom ┆ n_floors ┆ … ┆ is_exteri ┆ has_parki ┆ energy_ce ┆ house_typ │
│ t          ┆ ---     ┆ s          ┆ ---      ┆   ┆ or        ┆ ng        ┆ rtificate ┆ e         │
│ ---        ┆ i64     ┆ ---        ┆ i64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64        ┆         ┆ i64        ┆          ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64       │
╞════════════╪═════════╪════════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 64.0       ┆ 2       ┆ 1          ┆ 1        ┆ … ┆ 1         ┆ 0         ┆ 4         ┆ 0         │
│ 70.0       ┆ 3       ┆ 1          ┆ 1        ┆ … ┆ 1         ┆ 0         ┆ 0         ┆ 0         │
│ 94.0       ┆ 2       ┆ 2          ┆ 1        ┆ … ┆ 1         ┆ 0         ┆ 0         ┆ 0         │
│ 64.0       ┆ 2       ┆ 1          ┆ 1        ┆ … ┆ 1         ┆ 0         ┆ 0         ┆ 0         │
│ 108.0      ┆ 2       ┆ 2          ┆ 1        ┆ … ┆ 1         ┆ 1         ┆ 0         ┆ 0         │
└────────────┴─────────┴────────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [10]:
data_pd = pd.read_csv(data_path)
data_pd.head()

sq_mt_built  n_rooms  n_bathrooms  n_floors  buy_price  is_renewal_needed  \
0         64.0        2            1         1      85000                  0   
1         70.0        3            1         1     129900                  1   
2         94.0        2            2         1     144247                  0   
3         64.0        2            1         1     109900                  0   
4        108.0        2            2         1     260000                  0   

   has_lift  is_exterior  has_parking  energy_certificate  house_type  
0         0            1            0                   4           0  
1         1            1            0                   0           0  
2         1            1            0                   0           0  
3         1            1            0                   0           0  
4         1            1            1                   0           0

In [12]:
data_np = np.array(data_pd)
data_np

array([[ 64.,   2.,   1., ...,   0.,   4.,   0.],
       [ 70.,   3.,   1., ...,   0.,   0.,   0.],
       [ 94.,   2.,   2., ...,   0.,   0.,   0.],
       ...,
       [175.,   4.,   2., ...,   1.,   3.,   0.],
       [289.,   4.,   3., ...,   1.,   0.,   1.],
       [ 72.,   2.,   2., ...,   1.,   7.,   0.]])

- `euclidean_dist_matrix`

In [5]:
from PyDistances.quantitative import euclidean_dist_matrix

In [14]:
euclidean_dist_matrix(X=data_pl)

array([[     0.        ,  44900.00061247,  59247.00774723, ...,
        595000.01035966, 610000.04152049, 339000.00011209],
       [ 44900.00061247,      0.        ,  14347.02017842, ...,
        550100.01003363, 565100.04244735, 294100.00009691],
       [ 59247.00774723,  14347.02017842,      0.        , ...,
        535753.00613716, 550753.03453181, 279753.00095441],
       ...,
       [595000.01035966, 550100.01003363, 535753.00613716, ...,
             0.        ,  15000.43369373, 256000.02076172],
       [610000.04152049, 565100.04244735, 550753.03453181, ...,
         15000.43369373,      0.        , 271000.08699076],
       [339000.00011209, 294100.00009691, 279753.00095441, ...,
        256000.02076172, 271000.08699076,      0.        ]])

In [15]:
euclidean_dist_matrix(X=data_pd)

array([[     0.        ,  44900.00061247,  59247.00774723, ...,
        595000.01035966, 610000.04152049, 339000.00011209],
       [ 44900.00061247,      0.        ,  14347.02017842, ...,
        550100.01003363, 565100.04244735, 294100.00009691],
       [ 59247.00774723,  14347.02017842,      0.        , ...,
        535753.00613716, 550753.03453181, 279753.00095441],
       ...,
       [595000.01035966, 550100.01003363, 535753.00613716, ...,
             0.        ,  15000.43369373, 256000.02076172],
       [610000.04152049, 565100.04244735, 550753.03453181, ...,
         15000.43369373,      0.        , 271000.08699076],
       [339000.00011209, 294100.00009691, 279753.00095441, ...,
        256000.02076172, 271000.08699076,      0.        ]])

In [16]:
euclidean_dist_matrix(X=data_np)

array([[     0.        ,  44900.00061247,  59247.00774723, ...,
        595000.01035966, 610000.04152049, 339000.00011209],
       [ 44900.00061247,      0.        ,  14347.02017842, ...,
        550100.01003363, 565100.04244735, 294100.00009691],
       [ 59247.00774723,  14347.02017842,      0.        , ...,
        535753.00613716, 550753.03453181, 279753.00095441],
       ...,
       [595000.01035966, 550100.01003363, 535753.00613716, ...,
             0.        ,  15000.43369373, 256000.02076172],
       [610000.04152049, 565100.04244735, 550753.03453181, ...,
         15000.43369373,      0.        , 271000.08699076],
       [339000.00011209, 294100.00009691, 279753.00095441, ...,
        256000.02076172, 271000.08699076,      0.        ]])